import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const targetRouteShortNames = new Set(['3', '4', '8', '10', '11', '13', '15', '17', '18', '33', '35', '55', '56', '58', '61', '68']);

const gtfsDir = process.env.GTFS_STATIC_DIR;
const writeShapes = process.argv.includes('--write-shapes');

function parseCsv(text) {
  const rows = [];
  let row = [];
  let value = '';
  let quoted = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (quoted && char === '"' && next === '"') {
      value += '"';
      index += 1;
      continue;
    }
    if (char === '"') {
      quoted = !quoted;
      continue;
    }
    if (!quoted && char === ',') {
      row.push(value);
      value = '';
      continue;
    }
    if (!quoted && (char === '\n' || char === '\r')) {
      if (char === '\r' && next === '\n') index += 1;
      row.push(value);
      if (row.some((cell) => cell.length > 0)) rows.push(row);
      row = [];
      value = '';
      continue;
    }
    value += char;
  }

  if (value.length > 0 || row.length > 0) {
    row.push(value);
    rows.push(row);
  }

  const [headers = [], ...records] = rows;
  return records.map((record) =>
    Object.fromEntries(headers.map((header, index) => [header.trim(), record[index] ?? ''])),
  );
}

async function readGtfsTable(name, required = true) {
  if (!gtfsDir) return [];
  try {
    return parseCsv(await readFile(path.join(gtfsDir, `${name}.txt`), 'utf8'));
  } catch (error) {
    if (required) throw new Error(`Missing GTFS table ${name}.txt in ${gtfsDir}`);
    return [];
  }
}

function routeTypeLabel(routeType) {
  if (routeType === '0') return 'tram';
  if (routeType === '3') return 'bus';
  return `route_type:${routeType || 'unknown'}`;
}

function selectRepresentativeShapes(routes, trips, shapes) {
  const routesById = new Map(routes.map((route) => [route.route_id, route]));
  const shapePointCounts = shapes.reduce((counts, point) => {
    counts.set(point.shape_id, (counts.get(point.shape_id) ?? 0) + 1);
    return counts;
  }, new Map());

  const candidatesByRoute = new Map();
  trips.forEach((trip) => {
    const route = routesById.get(trip.route_id);
    if (!route || !trip.shape_id || !targetRouteShortNames.has(route.route_short_name)) return;
    const candidates = candidatesByRoute.get(route.route_short_name) ?? new Map();
    candidates.set(trip.shape_id, (candidates.get(trip.shape_id) ?? 0) + 1);
    candidatesByRoute.set(route.route_short_name, candidates);
  });

  return [...candidatesByRoute.entries()].map(([routeShortName, candidates]) => {
    const [shapeId, tripCount] = [...candidates.entries()].sort((a, b) => {
      const tripDelta = b[1] - a[1];
      if (tripDelta !== 0) return tripDelta;
      return (shapePointCounts.get(b[0]) ?? 0) - (shapePointCounts.get(a[0]) ?? 0);
    })[0];
    const route = routes.find((item) => item.route_short_name === routeShortName);

    return {
      routeShortName,
      routeId: route?.route_id ?? '',
      routeType: routeTypeLabel(route?.route_type),
      shapeId,
      tripCount,
      pointCount: shapePointCounts.get(shapeId) ?? 0,
    };
  });
}

function buildGeneratedShapeModule(representativeShapes, shapes) {
  const pointsByShape = shapes.reduce((groups, point) => {
    const points = groups.get(point.shape_id) ?? [];
    points.push(point);
    groups.set(point.shape_id, points);
    return groups;
  }, new Map());

  const shapeEntries = representativeShapes.map((shape) => {
    const points = (pointsByShape.get(shape.shapeId) ?? [])
      .sort((a, b) => Number(a.shape_pt_sequence) - Number(b.shape_pt_sequence))
      .map((point) => ({
        lat: Number(point.shape_pt_lat),
        lon: Number(point.shape_pt_lon),
      }))
      .filter((point) => Number.isFinite(point.lat) && Number.isFinite(point.lon));

    return {
      line: shape.routeShortName,
      routeId: shape.routeId,
      routeType: shape.routeType,
      shapeId: shape.shapeId,
      path: points,
    };
  });

  return `import type { LatLng } from '../types';

export type GtfsRouteShape = {
  line: string;
  routeId: string;
  routeType: string;
  shapeId: string;
  path: LatLng[];
};

// Generated by npm run realtime:spike -- --write-shapes from an authorized local GTFS static export.
// Do not edit by hand. Keep this file out of the active app until legal/technical validation is complete.
export const gtfsRouteShapes: GtfsRouteShape[] = ${JSON.stringify(shapeEntries, null, 2)};
`;
}

async function main() {
  const envSummary = {
    GTFS_STATIC_DIR: gtfsDir ? 'set' : 'missing',
    GTFS_RT_VEHICLE_POSITIONS_URL: process.env.GTFS_RT_VEHICLE_POSITIONS_URL ? 'set' : 'missing',
    GTFS_RT_TRIP_UPDATES_URL: process.env.GTFS_RT_TRIP_UPDATES_URL ? 'set' : 'missing',
    GTFS_RT_ALERTS_URL: process.env.GTFS_RT_ALERTS_URL ? 'set' : 'missing',
    GTFS_RT_API_KEY: process.env.GTFS_RT_API_KEY ? 'set' : 'missing',
  };

  if (!gtfsDir) {
    console.log(JSON.stringify({
      mode: 'documentation-only',
      env: envSummary,
      nextStep: 'Set GTFS_STATIC_DIR to an extracted, authorized GTFS static folder to inspect route shapes.',
    }, null, 2));
    return;
  }

  const [agency, routes, trips, stops, stopTimes, shapes] = await Promise.all([
    readGtfsTable('agency'),
    readGtfsTable('routes'),
    readGtfsTable('trips'),
    readGtfsTable('stops'),
    readGtfsTable('stop_times'),
    readGtfsTable('shapes'),
  ]);

  const representativeShapes = selectRepresentativeShapes(routes, trips, shapes);
  const summary = {
    mode: 'local-gtfs-static-inspection',
    env: envSummary,
    agency: agency.map((item) => ({ agency_name: item.agency_name, agency_url: item.agency_url })),
    counts: {
      routes: routes.length,
      trips: trips.length,
      stops: stops.length,
      stop_times: stopTimes.length,
      shapes: new Set(shapes.map((shape) => shape.shape_id)).size,
      shape_points: shapes.length,
    },
    representativeShapes,
  };

  if (writeShapes) {
    const outputPath = path.resolve('src/data/gtfsRouteShapes.generated.ts');
    await mkdir(path.dirname(outputPath), { recursive: true });
    await writeFile(outputPath, buildGeneratedShapeModule(representativeShapes, shapes));
    summary.generated = outputPath;
  }

  console.log(JSON.stringify(summary, null, 2));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
